```yaml
workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

      vars:
        BUNDLE_ID: "com.choumad.cvify"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log


  web-release:
    name: Web Release
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      flutter: stable

    cache:
      cache_paths:
        - ~/.pub-cache

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Run Flutter analyze
        script: flutter analyze --no-fatal-infos

      - name: Build web (release)
        script: |
          flutter build web \
            --release \
            --web-renderer canvaskit \
            --base-href /

    artifacts:
      - build/web/
```
